import Head from 'next/head';

import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h3>- <Link href='/jotai'>Jotai</Link></h3>
			<h3>- <Link href='/jotai2'>Jotai2</Link></h3>
		</div>
	);
}
